Adding type hints and improving docs
PhilipEHausner/python_heideltime pull request #2
Opened 2022-03-30 15:06 UTC by dennlinger

Added type hints to move descriptive comments into actual tangible programming feedback; e.g., it was unclear what type the "document time" should be in. Clarifying that it is a string already helps enormously.  
Also added in comments that should show up during function previews to help clarify what parameters are possible, or what the specific format should be.  
For some parameters, also added direct feedback from Python that raise Errors when inputting incorrect values (if available choices exist in the original Heideltime docs), or help with upper/lowercasing.

I haven't verified whether the hints actually show up (yet), but am planning on at least extending it to a usable state.
@PhilipEHausner: Let me know if you want a more "thorough" PR, happy to add stuff before merging.

2022-03-30 18:09 UTC, PhilipEHausner commented on python_heideltime/python_heideltime.py
> +                       'ARABIC', 'VIETNAMESE', 'FRENCH', 'CHINESE', 'RUSSIAN', 'CROATIAN', 'PORTUGUESE', 'ESTONIAN']
Personally I would order the languages alphabetically.

2022-03-30 18:10 UTC, PhilipEHausner commented on python_heideltime/python_heideltime.py
> +            raise ValueError('Incorrect format for document time specified. Please use the \"YYYY-MM-DD\" format.')
I think the "s do not need to be escaped here.

2022-03-30 18:11 UTC, PhilipEHausner commented on python_heideltime/python_heideltime.py
> +                             f'{AVAILABLE_LANGUAGES}')
Maybe also add what the passed parameter was.

2022-03-30 18:11 UTC, PhilipEHausner commented on python_heideltime/python_heideltime.py
> +                             f'types: {AVAILABLE_DOCUMENT_TYPES}')
same as with language

2022-03-30 18:42 UTC, PhilipEHausner commented on python_heideltime/python_heideltime.py
> +                             f'{AVAILABLE_OUTPUT_TYPES}')
as above

2022-03-30 18:43 UTC, PhilipEHausner commented on python_heideltime/python_heideltime.py
>      def set_encoding(self, encoding):
type hints

2022-03-30 18:43 UTC, PhilipEHausner commented on python_heideltime/python_heideltime.py
> +    # FIXME: Technically, Heideltime supports two different verbosity levels, which we cannot model here.
Maybe specify here what you mean with that. I would not remember what I meant here a month alter. ;)

2022-03-30 18:46 UTC, PhilipEHausner requested changes
Thank you for putting up the effort to improve the tool. I would ask you, however, to also add return types to the functions. I know it is always None, but static type checkers expect that if you have type hints you also need a return type (at least with the exception of the constructor I think).

Otherwise I only have minor comments.

2022-03-30 20:17 UTC, dennlinger commented
Addressed all comments, let me know if you have any further ideas.
As for the explanation in the FIXME, feel free to add further comments if it is still unclear.

2022-04-01 16:16 UTC, PhilipEHausner approved these changes

2022-04-01 16:16 UTC, merged